version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: workforce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sic300445!
      MYSQL_DATABASE: workforce
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./Dump20251120.sql:/docker-entrypoint-initdb.d/init.sql
